// DO NOT EDIT — generated by scripts/generate-language-map.js
// Run `npm run generate:languages` to regenerate.

export const languages = [
  'English',
  'French',
  'German',
  'Italian',
  'Russian',
  'Spanish',
  'Turkish',
] as const;

export type Language = (typeof languages)[number];

export const levels = ['A1', 'A2', 'B1', 'B2', 'C1'] as const;

export interface LanguageMeta {
  code: string;
  flag: string;
}

export const availableCombinations: Record<Language, Language[]> = {
  'English': ['French', 'German', 'Italian', 'Russian', 'Spanish', 'Turkish'],
  'French': ['English', 'German', 'Italian', 'Russian', 'Spanish', 'Turkish'],
  'German': ['English', 'French', 'Italian', 'Russian', 'Spanish', 'Turkish'],
  'Italian': ['English', 'French', 'German', 'Russian', 'Spanish', 'Turkish'],
  'Russian': ['English', 'French', 'German', 'Italian', 'Spanish', 'Turkish'],
  'Spanish': ['English', 'French', 'German', 'Italian', 'Russian', 'Turkish'],
  'Turkish': ['English', 'French', 'German', 'Italian', 'Russian', 'Spanish'],
};

export const LANGUAGE_META: Record<Language, LanguageMeta> = {
  'English': { code: 'en', flag: '🇬🇧' },
  'French': { code: 'fr', flag: '🇫🇷' },
  'German': { code: 'de', flag: '🇩🇪' },
  'Italian': { code: 'it', flag: '🇮🇹' },
  'Russian': { code: 'ru', flag: '🇷🇺' },
  'Spanish': { code: 'es', flag: '🇪🇸' },
  'Turkish': { code: 'tr', flag: '🇹🇷' },
};
